### ISSUE TITLE
Cannot add custom counter: You do not have permission to call the "log.info" function

### ISSUE THREAD

**Issue by iggyvolz** [melek/Simple5e#15]
**Describe the bug**
Attempting to add a custom counter gives: `You do not have permission to call the "log.info" function.`, without opening the window.

**To Reproduce**
1. On fresh Simple5e 2.1 campaign (also verified with 2.0), click on Standard Token> GM > Custom Counters
2. Click Add New Counter
3. No window pops up, and `You do not have permission to call the "log.info" function.` shows in chat.

**Expected behavior**
Custom Counter creation window should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/2197376/82348241-945e3e00-99c6-11ea-8893-182ef3d64eba.png)

**Desktop (please complete the following information):**
 - OS & Version: Windows 10 (Version 10.0.18363.836)
 - MapTool Version: 1.7.0
 - MapTool Install type: Ran installer to upgrade from beta2 => stable

**Additional context**
Bug was not present with MapTool 1.7.0 betas, just tried downgrading to beta2 and the bug was not present.

**Comment by iggyvolz** [comment]
Bug is present with beta3 but not beta2.

Changing `[h: vInfo = isGm()]` to`[h: vInfo = 0]` in the Custom Counters macro works around the issue for now

**Comment by melek** [comment]
Thanks for sharing this and your workaround! I'm inclined to think this is a new bug introduced by MT 1.7. I use that `vInfo` pattern a few times so I'm curious if other areas are affected. :(

**Comment by melek** [comment]
Since this issue only affects 1.7 as far as I can tell with testing, I'm putting in some simple conditional code to disable the error logging in 1.7.

**Comment by melek** [comment]
Okay, most of the GM panel macros used the `vInfo` pattern. 1.8 should have this trusted macro issue fixed, so 1.7.0 will be the only version that has this bug. 

I've replaced each instance of `[h: vInfo = isGM()]` with:
`[h: vInfo = if(json.get(getInfo("client"), "version") == "1.7.0", 0, isGM())]`

- [x] Added to Campaign File
- [x] Added to Update Token
- [ ] Tested in 1.8.0b
- Not adding to Wiki (Documented here)

**Comment by melek** [comment]
I've decided to move this forward; if the problem arises in 1.8.0, we will deal with it then!
