### ISSUE TITLE
Feature Request: Add a healing die roll to Custom Action options

### ISSUE THREAD

**Issue by rogue-ronin** [melek/Simple5e#17]
**Is your feature request related to a problem? Please describe.**
I made a _Healing Light_ (Celestial Warlock Class Feature) Custom Counter and a matching Custom Action. I was hoping to add a die roll (1d6) for each counter used but I could only choose to damage.

**Describe the solution you'd like**
A healing option alongside the damage option.

**Describe alternatives you've considered**
I took a look at the damage one to see if I could use it, but... :)

**Additional context**
This might be useful for other abilities, like the Paladin's _Lay on Hands_ or for _Goodberry_

Well, maybe not _Goodberry_, but _Magic Initiate_ would have a counter of 1 and could have either _Cure Wounds_ or _Healing Word_.  Maybe a Healer's Kit on a character with the _Healer_ feat.

I can think of one magic item, too: a _Staff of Healing_ has 10 charges and can cast _Cure Wounds_ and _Mass Cure Wounds_.

Late edit: And now that I think of it, if you have a Custom Counter for your spell slots, a Custom Action to cast Cure Wounds or any other healing spell could link to that counter. (Man, you've made a clever, flexible thing!)

**Comment by melek** [comment]
Hi Rogue,
So looking at this request, I'm considering simply documenting how to do this with the current system - though updating the macros to teach people how to do it might be worthwhile.

To make a healing spell, say 'Healing Word', first - as you say - you must add the spell slot as a counter. Once done, create an action with only the Counter Cost checked:
![image](https://user-images.githubusercontent.com/220149/88983853-f10c8d80-d280-11ea-92e4-abfd08199fe6.png)

Next, simply edit the action output to include the die roll:
![image](https://user-images.githubusercontent.com/220149/88983895-11d4e300-d281-11ea-96c3-b9c9aac4d5b8.png)

Now when clicked, the new action button will trigger as long as the counter is available:
![image](https://user-images.githubusercontent.com/220149/88983967-37fa8300-d281-11ea-83e1-b96ef854a691.png)

Do you think this is adequate? Where could I add a tooltip or something to help players do this?

**Comment by melek** [comment]
I am closing this for now. Adding documentation to the Wiki about how to do this might be helpful down the road, but I'm not sure how many people look there. Hopefully this issue and the suggested workaround will help people looking to add healing spells!
