### ISSUE TITLE
Provide pre-made macros for SRD weapons

### ISSUE THREAD

**Issue by Merudo** [melek/Simple5e#18]
**Is your feature request related to a problem? Please describe.**

Currently, DMs and players need to manually create macros for each of their weapon. This is tedious and error prone.

**Describe the solution you'd like**
The SRD includes information about most non-magical weapons. It would be great to have pre-built macros for those weapons.

These macros could be accessible by pressing the "Create Action" button and selecting the desired weapon in a drop-down menu.

**Comment by melek** [comment]
Good point. Perhaps a dead-simple JSON could provide this as a tab (Quick weapon macros?) in the existing 'Create Action' macro.

**Comment by melek** [comment]
Or.. how does it sound to select a template weapon and then get to review/edit its values? This way a magic longsword will be easy to add its +1 to...

I'll play around with the idea a little to see what feels fluid.

**Comment by melek** [comment]
I've gone with a simple approach of letting players select an SRD weapon template that auto-populates values. Weapon properties are saved in the action with the tooltip. Additionally, users can now add tooltip notes to themselves as well.

This still requires a lot of clicks to add a weapon, but the wizard selects the correct attribute (STR, DEX, or the highest of the two if the weapon is Finesse), fills out the damage, and if the defaults are left alone it will automatically produce a simple, non-magical weapon macro when the player simply hits 'ok' on all pages. 

Perhaps a further enhancement will be a 'quick weapon' checkbox that will skip as much as possible, but for now this is enough.

- [x] Added to Campaign File
- [x] Added to Update Token
- Not adding to Wiki
