### ISSUE TITLE
Jack of all trades

### ISSUE THREAD

**Issue by inklikeurine** [melek/Simple5e#20]
**Is your feature request related to a problem? Please describe.**
Jack of All Trades is a popular feature and would be nice to implement in the framework.

**Describe the solution you'd like**
A single button toggle for Jack of All Trades in the character sheet setup

**Describe alternatives you've considered**
None

**Comment by melek** [comment]
In the interest of keeping the Configure Token macro lean, I've kept this functionality as a separate macro that lives on the GM panel. It will be part of Simple5e 2.2.

This functionality is available now as a downloadable macro on the Simple5e Wiki: 
https://github.com/melek/Simple5e/wiki/Customizing-Simple5e:-Adding-Bard's-'Jack-of-all-Trades'

- [x] Added to Campaign File
- [x] Added to Update Token
- [x] Added to Wiki
