### ISSUE TITLE
Invisibility state doesn't reset properly when Remove All is used.

### ISSUE THREAD

**Issue by rogue-ronin** [melek/Simple5e#5]
**Describe the bug**
Invisibility state doesn't reset properly when Remove All is used.

**To Reproduce**

1. Select an NPC token
2. In the Campaign Macros window, set Invisibility using the macro button
3. In the Campaign Macros window, remove Invisibility by using the Remove All macro button
4. In the Campaign Macros window, set Invisibility using the macro button
5. In the Chat window, the phrase "NPC appears" is emitted.
6. On the NPC, no state icon appears.

**Expected behavior**
At step 5 we should see the Invisibility state described in the Chat.
At step 6 we should see the Invisibility state icon appear on the NPC.

**Desktop (please complete the following information):**
==== MapTool Information ====
MapTool Version: 1.6.1
MapTool Home...: /home/rogue/.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 314 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: /opt/MapTool/runtime
Java Version: 10.0.2

==== OS Information ====
OS Name........: Linux
OS Version.....: 5.6.8-1-MANJARO
OS Architecture: amd64
PATH...........: /home/rogue/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
Number of Procs: 4

==== Locale Information ====
Country.: United States
Language: 
Locale..: United States
Variant.: 

==== Encoding Information ====
Default Locale:   _US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

**Additional context**
Fairly fresh install as I experiment and build my default campaign file.

**Comment by melek** [comment]
The Remove All state also doesn't remove a few other state related properties; specifically, death save failures and successes.

Will fix.

**Comment by melek** [comment]
Huh, I guess it actually did already clear death saves! I've fixed 'Remove All' to unset `setOnlyOwnersVisible` if a token is invisible.

I've also found that the old 'Invisibility' macro doesn't hide rules from players if the GM clicks it, I will open a new issue for that.

- [x] Fixed in 2.1 Campaign File
- [ ] Wiki updated with fix
- [ ] Patch token updated
