### ISSUE TITLE
Players see remaining HP of NPCs when using Damage NPC macro

### ISSUE THREAD

**Issue by Merudo** [melek/Simple5e#7]
**Describe the bug**
Players see the remaining and total HP of NPCs when using the `Damage NPC` macro. This info should be only be available to the GM.

**To Reproduce**
1. As a player, use the Damage NPC macro on a NPC
2. The output you get gives a lot of info: `Dragon's updated HP: 8/10 (took 1)`

**Comment by melek** [comment]
Thanks for catching this; I'm a bit surprised nobody had complained about it before!

**Comment by melek** [comment]
I've added checks to the Damage NPC and Heal NPC macros to prevent players from running them on tokens they do not own. When run on their own tokens, they will work nearly identically to the Heal/damage macros on their own tokens.

I almost added similar code to Roll Initiative and any conditions that might change properties, but decided not to add the weight (and code duplication).

- [x] Update Campaign File
- [ ] Update Wiki
- [ ] Update Update Token

**Comment by melek** [comment]
Waiting on #10 to close.
